[versions]
cohort = "2.8.2"
detekt = "2.0.0-alpha.2"
fabrikt = "25.8.0"
hikari = "7.0.2"
jooq = "3.20.11"
koin = "4.1.1"
kotest = "6.1.3"
kotlin = "2.3.10"
kotlin-logging = "7.0.14"
kotlin-result = "2.1.0"
kotlinx-coroutines = "1.10.2"
kotlinx-datetime = "0.7.1"
ktor = "3.4.0"
lettuce = "7.4.0.RELEASE"
logback = "1.5.31"
micrometer = "1.16.3"
postgresql = "42.7.10"
testcontainers = "2.0.3"

[libraries]
cohort-hikari = { module = "com.sksamuel.cohort:cohort-hikari", version.ref = "cohort" }
cohort-ktor = { module = "com.sksamuel.cohort:cohort-ktor", version.ref = "cohort" }
cohort-micrometer = { module = "com.sksamuel.cohort:cohort-micrometer", version.ref = "cohort" }
fabrikt = { module = "com.cjbooms:fabrikt", version.ref = "fabrikt" }
hikari = { module = "com.zaxxer:HikariCP", version.ref = "hikari" }
jooq-kotlin = { module = "org.jooq:jooq-kotlin", version.ref = "jooq" }
jooq-kotlin-coroutines = { module = "org.jooq:jooq-kotlin-coroutines", version.ref = "jooq" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-ktor = { module = "io.insert-koin:koin-ktor" }
koin-logger-slf4j = { module = "io.insert-koin:koin-logger-slf4j" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotlin-logging-jvm = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result" }
kotlin-result-coroutines = { module = "com.michael-bull.kotlin-result:kotlin-result-coroutines", version.ref = "kotlin-result" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-reactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation" }
ktor-client-core = { module = "io.ktor:ktor-client-core" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth" }
ktor-server-call-id = { module = "io.ktor:ktor-server-call-id" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging" }
ktor-server-config-yaml = { module = "io.ktor:ktor-server-config-yaml" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation" }
ktor-server-core = { module = "io.ktor:ktor-server-core" }
ktor-server-cors = { module = "io.ktor:ktor-server-cors" }
ktor-server-metrics-micrometer = { module = "io.ktor:ktor-server-metrics-micrometer" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages" }
ktor-server-swagger = { module = "io.ktor:ktor-server-swagger" }
ktor-server-test-host = { module = "io.ktor:ktor-server-test-host", version.ref = "ktor" }
lettuce-core = { module = "io.lettuce:lettuce-core", version.ref = "lettuce" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
micrometer-registry-prometheus = { module = "io.micrometer:micrometer-registry-prometheus", version.ref = "micrometer" }
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
testcontainers = { module = "org.testcontainers:testcontainers", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:testcontainers-postgresql", version.ref = "testcontainers" }

[bundles]
cohort = [
    "cohort-hikari",
    "cohort-ktor",
    "cohort-micrometer",
]

jooq = [
    "jooq-kotlin",
    "jooq-kotlin-coroutines",
]

koin = [
    "koin-core",
    "koin-logger-slf4j",
    "koin-ktor",
]

kotest = [
    "kotest-assertions-core",
    "kotest-runner-junit5",
]

kotlin-result = [
    "kotlin-result",
    "kotlin-result-coroutines",
]

kotlinx-coroutines = [
    "kotlinx-coroutines-core",
    "kotlinx-coroutines-reactive",
]

ktor-client = [
    "ktor-client-apache5",
    "ktor-client-content-negotiation",
    "ktor-client-core",
    "ktor-client-logging",
]

ktor-server = [
    "ktor-serialization",
    "ktor-server-auth",
    "ktor-server-call-id",
    "ktor-server-call-logging",
    "ktor-server-config-yaml",
    "ktor-server-content-negotiation",
    "ktor-server-core",
    "ktor-server-cors",
    "ktor-server-metrics-micrometer",
    "ktor-server-netty",
    "ktor-server-sessions",
    "ktor-server-status-pages",
    "ktor-server-swagger",
]

testcontainers = [
    "testcontainers",
    "testcontainers-postgresql"
]

[plugins]
detekt = { id = "dev.detekt", version.ref = "detekt" }
jooq-codegen = { id = "org.jooq.jooq-codegen-gradle", version.ref = "jooq" }
kotest = { id = "io.kotest", version.ref = "kotest" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktor = { id = "io.ktor.plugin", version.ref = "ktor" }
